import React from 'react';
import Section from '../Section';
import "../../stylesheets/Blog.css";

const Blog = () => {
  return (
    <Section scrollable={true}>
      <h1>Blog</h1>
      <h2>10/10/2023</h2>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore fuga exercitationem ipsam. Sapiente eaque quasi blanditiis officia placeat, consectetur voluptate amet rem id corporis praesentium saepe repudiandae laudantium dignissimos quos nihil minima quia vitae rerum, porro iure! Aspernatur voluptate asperiores ipsum odit eveniet adipisci reprehenderit cum dolore iure maiores sequi, atque, tenetur provident quisquam beatae iste, alias sint ex. Quis at dicta delectus ducimus commodi dolorem nobis optio voluptatem iure mollitia eligendi sequi necessitatibus sapiente, laboriosam cumque consequatur alias cupiditate culpa quidem vero explicabo. Laborum, nulla autem ipsam a soluta esse! Cum ullam nesciunt doloribus a, earum iste quia voluptatum?</p>
      <h2>10/10/2023</h2>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore fuga exercitationem ipsam. Sapiente eaque quasi blanditiis officia placeat, consectetur voluptate amet rem id corporis praesentium saepe repudiandae laudantium dignissimos quos nihil minima quia vitae rerum, porro iure! Aspernatur voluptate asperiores ipsum odit eveniet adipisci reprehenderit cum dolore iure maiores sequi, atque, tenetur provident quisquam beatae iste, alias sint ex. Quis at dicta delectus ducimus commodi dolorem nobis optio voluptatem iure mollitia eligendi sequi necessitatibus sapiente, laboriosam cumque consequatur alias cupiditate culpa quidem vero explicabo. Laborum, nulla autem ipsam a soluta esse! Cum ullam nesciunt doloribus a, earum iste quia voluptatum?</p>
      <h2>10/10/2023</h2>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore fuga exercitationem ipsam. Sapiente eaque quasi blanditiis officia placeat, consectetur voluptate amet rem id corporis praesentium saepe repudiandae laudantium dignissimos quos nihil minima quia vitae rerum, porro iure! Aspernatur voluptate asperiores ipsum odit eveniet adipisci reprehenderit cum dolore iure maiores sequi, atque, tenetur provident quisquam beatae iste, alias sint ex. Quis at dicta delectus ducimus commodi dolorem nobis optio voluptatem iure mollitia eligendi sequi necessitatibus sapiente, laboriosam cumque consequatur alias cupiditate culpa quidem vero explicabo. Laborum, nulla autem ipsam a soluta esse! Cum ullam nesciunt doloribus a, earum iste quia voluptatum?</p>
      <h2>10/10/2023</h2>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore fuga exercitationem ipsam. Sapiente eaque quasi blanditiis officia placeat, consectetur voluptate amet rem id corporis praesentium saepe repudiandae laudantium dignissimos quos nihil minima quia vitae rerum, porro iure! Aspernatur voluptate asperiores ipsum odit eveniet adipisci reprehenderit cum dolore iure maiores sequi, atque, tenetur provident quisquam beatae iste, alias sint ex. Quis at dicta delectus ducimus commodi dolorem nobis optio voluptatem iure mollitia eligendi sequi necessitatibus sapiente, laboriosam cumque consequatur alias cupiditate culpa quidem vero explicabo. Laborum, nulla autem ipsam a soluta esse! Cum ullam nesciunt doloribus a, earum iste quia voluptatum?</p>
      <h2>10/10/2023</h2>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore fuga exercitationem ipsam. Sapiente eaque quasi blanditiis officia placeat, consectetur voluptate amet rem id corporis praesentium saepe repudiandae laudantium dignissimos quos nihil minima quia vitae rerum, porro iure! Aspernatur voluptate asperiores ipsum odit eveniet adipisci reprehenderit cum dolore iure maiores sequi, atque, tenetur provident quisquam beatae iste, alias sint ex. Quis at dicta delectus ducimus commodi dolorem nobis optio voluptatem iure mollitia eligendi sequi necessitatibus sapiente, laboriosam cumque consequatur alias cupiditate culpa quidem vero explicabo. Laborum, nulla autem ipsam a soluta esse! Cum ullam nesciunt doloribus a, earum iste quia voluptatum?</p>
      <h2>10/10/2023</h2>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore fuga exercitationem ipsam. Sapiente eaque quasi blanditiis officia placeat, consectetur voluptate amet rem id corporis praesentium saepe repudiandae laudantium dignissimos quos nihil minima quia vitae rerum, porro iure! Aspernatur voluptate asperiores ipsum odit eveniet adipisci reprehenderit cum dolore iure maiores sequi, atque, tenetur provident quisquam beatae iste, alias sint ex. Quis at dicta delectus ducimus commodi dolorem nobis optio voluptatem iure mollitia eligendi sequi necessitatibus sapiente, laboriosam cumque consequatur alias cupiditate culpa quidem vero explicabo. Laborum, nulla autem ipsam a soluta esse! Cum ullam nesciunt doloribus a, earum iste quia voluptatum?</p>
      <h2>10/10/2023</h2>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore fuga exercitationem ipsam. Sapiente eaque quasi blanditiis officia placeat, consectetur voluptate amet rem id corporis praesentium saepe repudiandae laudantium dignissimos quos nihil minima quia vitae rerum, porro iure! Aspernatur voluptate asperiores ipsum odit eveniet adipisci reprehenderit cum dolore iure maiores sequi, atque, tenetur provident quisquam beatae iste, alias sint ex. Quis at dicta delectus ducimus commodi dolorem nobis optio voluptatem iure mollitia eligendi sequi necessitatibus sapiente, laboriosam cumque consequatur alias cupiditate culpa quidem vero explicabo. Laborum, nulla autem ipsam a soluta esse! Cum ullam nesciunt doloribus a, earum iste quia voluptatum?</p>
      <h2>10/10/2023</h2>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore fuga exercitationem ipsam. Sapiente eaque quasi blanditiis officia placeat, consectetur voluptate amet rem id corporis praesentium saepe repudiandae laudantium dignissimos quos nihil minima quia vitae rerum, porro iure! Aspernatur voluptate asperiores ipsum odit eveniet adipisci reprehenderit cum dolore iure maiores sequi, atque, tenetur provident quisquam beatae iste, alias sint ex. Quis at dicta delectus ducimus commodi dolorem nobis optio voluptatem iure mollitia eligendi sequi necessitatibus sapiente, laboriosam cumque consequatur alias cupiditate culpa quidem vero explicabo. Laborum, nulla autem ipsam a soluta esse! Cum ullam nesciunt doloribus a, earum iste quia voluptatum?</p>
    </Section>
  );
};

export default Blog;